name: shanyao
version: 0.0.1.0
github: "vaclavsvejcar/shanyao"
license: BSD3
author: Vaclav Svejcar
maintainer: vaclav.svejcar@gmail.com
copyright: 2020 Vaclav Svejcar

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/vaclavsvejcar/shanyao#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  shanyao:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - shanyao

tests:
  shanyao-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - shanyao
